# Generated by Django 6.0.7 on 2026-07-10 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('OWASP', 'OWASP'), ('CWE', 'CWE'), ('SEMGREP_DOC', 'Semgrep Doc'), ('TRIVY_DOC', 'Trivy Doc'), ('CUSTOM_NOTE', 'Custom Note'), ('RUNBOOK', 'Runbook')], max_length=50)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'knowledge_base_document',
                'indexes': [models.Index(fields=['source_type', 'active'], name='knowledge_b_source__7e66f1_idx'), models.Index(fields=['category'], name='knowledge_b_categor_9e6a74_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('embedding_json', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_base.knowledgedocument')),
            ],
            options={
                'db_table': 'knowledge_base_chunk',
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='knowledge_b_documen_61cc7a_idx'), models.Index(fields=['created_date'], name='knowledge_b_created_50e750_idx')],
            },
        ),
    ]
