# Generated by Django 6.0.7 on 2026-07-10 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('source_file', models.FileField(upload_to='source_uploads/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('scan_type', models.CharField(choices=[('SAST', 'SAST'), ('DEPENDENCY', 'Dependency'), ('FULL', 'Full')], default='FULL', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_jobs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to='projects.project')),
            ],
            options={
                'db_table': 'scans_scan_job',
                'indexes': [models.Index(fields=['project', 'status'], name='scans_scan__project_c096d2_idx'), models.Index(fields=['created_by'], name='scans_scan__created_244343_idx'), models.Index(fields=['created_date'], name='scans_scan__created_012ea9_idx')],
            },
        ),
    ]
