# Generated by Django 6.0.7 on 2026-07-10 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField()),
                ('risk_overview', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('report_json', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('scan_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_report', to='scans.scanjob')),
            ],
            options={
                'db_table': 'ai_agents_ai_report',
                'indexes': [models.Index(fields=['created_date'], name='ai_agents_a_created_bd7be6_idx')],
            },
        ),
    ]
