# Generated by Django 6.0.7 on 2026-07-10 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('scanner_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('code_snippet', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FIXED', 'Fixed'), ('IGNORED', 'Ignored')], default='OPEN', max_length=20)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scans.scanjob')),
            ],
            options={
                'db_table': 'findings_scan_finding',
                'indexes': [models.Index(fields=['scan_job', 'severity'], name='findings_sc_scan_jo_a69afb_idx'), models.Index(fields=['status'], name='findings_sc_status_1930c5_idx'), models.Index(fields=['scanner_name'], name='findings_sc_scanner_2687b2_idx')],
            },
        ),
    ]
